# Generated by Django 5.2 on 2026-02-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_member_id_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_type', models.CharField(choices=[('POKOK', 'Simpanan Pokok'), ('WAJIB', 'Simpanan Wajib'), ('SUKARELA', 'Simpanan Sukarela')], max_length=20)),
                ('saving_id', models.CharField(max_length=50, unique=True)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('transfer_proof', models.FileField(upload_to='transfer_proofs/')),
                ('member_bank_name', models.CharField(max_length=100)),
                ('member_account_number', models.CharField(max_length=50)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
