# Generated by Django 5.2 on 2026-02-25 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_member_id_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('transaction_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('saving_type', models.CharField(choices=[('PRINCIPAL', 'Simpanan Pokok'), ('MANDATORY', 'Simpanan Wajib'), ('VOLUNTARY', 'Simpanan Sukarela')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('proof_image', models.ImageField(upload_to='savings/proofs/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.bankaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='members.member')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_savings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
