# Generated by Django 6.0.2 on 2026-06-01 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_bankaccount_id_alter_member_id'),
        ('savings', '0004_savingswithdrawal_processing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandatorySavingObligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default='100000.00', max_digits=14)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandatory_saving_obligations', to='members.member')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mandatory_saving_obligations', to='savings.savingtransaction')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('member', 'period_start')},
            },
        ),
        migrations.AddField(
            model_name='savingtransaction',
            name='mandatory_obligation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saving_transactions', to='savings.mandatorysavingobligation'),
        ),
    ]
