# Generated by Django 6.0.2 on 2026-06-02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_mandatorysavingobligation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandatorysavingobligation',
            name='payment_method',
            field=models.CharField(
                choices=[('MANUAL', 'Manual'), ('AUTO_DEBIT', 'Auto Debit')],
                default='MANUAL',
                max_length=20,
            ),
        ),
    ]
