# Generated by Django 6.0.2 on 2026-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us Configuration',
            },
        ),
        migrations.CreateModel(
            name='CooperativeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_holder', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cooperative Bank Account',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Empowering Your Financial Future with', max_length=255)),
                ('brand_name', models.CharField(default='SI-MAPAN', max_length=100)),
                ('description', models.TextField(default='A secure and transparent platform for managing community savings and loans.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='config/hero/')),
                ('cta_text', models.CharField(default='Register as Member', max_length=50)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Nama icon (misal: 'pi-wallet')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
