# Generated by Django 6.0.2 on 2026-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='cta_text',
            field=models.CharField(default='Daftar sebagai Anggota', max_length=50),
        ),
        migrations.AlterField(
            model_name='landingpageconfig',
            name='description',
            field=models.TextField(default='Platform aman dan transparan untuk mengelola simpan pinjam masyarakat.'),
        ),
        migrations.AlterField(
            model_name='landingpageconfig',
            name='title',
            field=models.CharField(default='Mewujudkan Masa Depan Keuangan Anda Bersama', max_length=255),
        ),
    ]
