# Generated by Django 6.0.2 on 2026-03-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_aboutconfig_faq_landingpageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Nama icon (misal: 'pi-wallet')", max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
