# Generated by Django 5.2 on 2026-03-26 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_bankaccount_id_alter_member_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('MODAL_USAHA', 'Modal Usaha'), ('PENDIDIKAN', 'Pendidikan'), ('KESEHATAN', 'Kesehatan'), ('RENOVASI_RUMAH', 'Renovasi Rumah'), ('KENDARAAN', 'Kendaraan'), ('ELEKTRONIK', 'Elektronik'), ('PERNIKAHAN', 'Pernikahan'), ('DANA_DARURAT', 'Dana Darurat'), ('LAINNYA', 'Lainnya')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenor', models.IntegerField(choices=[(6, '6 Bulan'), (12, '12 Bulan'), (24, '24 Bulan'), (36, '36 Bulan')])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('LUNAS', 'Lunas'), ('OVERDUE', 'Overdue'), ('LUNAS_AFTER_OVERDUE', 'Lunas After Overdue')], default='PENDING', max_length=30)),
                ('collateral_image', models.ImageField(blank=True, null=True, upload_to='loans/collateral/')),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='loans/salary/')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_proof', models.ImageField(blank=True, null=True, upload_to='loans/disbursement/')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='members.bankaccount')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='BadDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WARNING_SENT', 'Warning Sent'), ('LEGAL_NOTICE', 'Legal Notice'), ('VISIT_SCHEDULED', 'Visit Scheduled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bad_debt', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING', 'Pending'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('transfer_proof', models.FileField(blank=True, null=True, upload_to='loans/payments/')),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_payments', to='members.bankaccount')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_installments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
