# Generated by Django 6.0.2 on 2026-06-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_note',
            field=models.TextField(blank='', null=True),
        ),
    ]
