# Generated by Django 6.0.2 on 2026-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='selfie/'),
        ),
    ]
