# Generated by Django 6.0.2 on 2026-03-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='has_paid_pokok',
            field=models.BooleanField(default=False),
        ),
    ]
