# Generated by Django 5.2 on 2026-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('SAVING', 'Saving'), ('LOAN', 'Loan'), ('RESIGNATION', 'Resignation'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
