# Generated by Django 6.0.2 on 2026-06-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('SAVING', 'Saving'), ('LOAN', 'Loan'), ('RESIGNATION', 'Resignation'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
