# Generated by Django 6.0.2 on 2026-06-01 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_id_alter_notification_type'),
        ('notifications', '0004_alter_notification_type'),
    ]

    operations = [
    ]
